Add custom svg components for lock and flash decorators
powsybl/powsybl-single-line-diagram-server pull request #48
Opened 2021-05-27 09:45 UTC by SlimaneAmar

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ x] The commit message follows our guidelines

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
Lock and flash decorators use the default svg components

**What is the new behavior (if this is a feature change)?**
Lock and flash decorators use the custom svg components

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*
No

2021-06-01 09:43 UTC, FranckLecuyer requested changes

2021-06-01 09:43 UTC, FranckLecuyer commented on src/main/resources/GridsuiteLibrary/lock_black_24dp.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g fill="none"><path d="M0 0h24v24H0V0z"/><path d="M0 0h24v24H0V0z" opacity=".87"/></g><path d="M
Maybe add newline at end of file ?

2021-06-01 09:43 UTC, FranckLecuyer commented on src/main/resources/GridsuiteLibrary/bolt_black_24dp.svg
> +<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g><rect fill="none" height="24" width="24"/></g><g><path d="M1
Maybe add newline at end of file ?

2021-06-07 07:23 UTC, SlimaneAmar commented on src/main/resources/GridsuiteLibrary/bolt_black_24dp.svg
> +<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g><rect fill="none" height="24" width="24"/></g><g><path d="M1
Done

2021-06-07 07:23 UTC, SlimaneAmar commented on src/main/resources/GridsuiteLibrary/lock_black_24dp.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g fill="none"><path d="M0 0h24v24H0V0z"/><path d="M0 0h24v24H0V0z" opacity=".87"/></g><path d="M
Done

2021-06-07 07:24 UTC, geofjamg approved these changes

2021-06-07 07:26 UTC, merged